# Generated by Django 3.2.5 on 2021-07-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageRecipient',
            new_name='Chat',
        ),
    ]
