# Generated by Django 3.2.5 on 2021-07-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0002_rename_messagerecipient_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
