# Generated by Django 3.2.5 on 2021-07-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0002_auto_20210714_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='connection_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
    ]
