# Generated by Django 3.2.5 on 2021-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0003_auto_20210711_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
