# Generated by Django 3.2.5 on 2021-07-15 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0003_auto_20210714_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator_id2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
