# Generated by Django 3.2.5 on 2021-07-15 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0004_post_creator_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator_id2',
        ),
        migrations.AlterField(
            model_name='post',
            name='creator_id',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
