# Generated by Django 3.2.5 on 2021-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0004_alter_member_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
    ]
