# Generated by Django 3.2.5 on 2021-07-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0007_alter_member_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_hub.chat'),
        ),
    ]
