# Generated by Django 3.2.5 on 2021-07-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0010_auto_20210711_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='recipient_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='member_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_1', to='edu_hub.member'),
        ),
        migrations.AddField(
            model_name='chat',
            name='member_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_2', to='edu_hub.member'),
        ),
    ]
