# Generated by Django 3.2.5 on 2021-07-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0013_auto_20210711_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to='edu_hub.member'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to='edu_hub.member'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
