# Generated by Django 3.2.5 on 2021-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0014_auto_20210712_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
