# Generated by Django 3.2.5 on 2021-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0015_alter_member_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
