# Generated by Django 3.2.5 on 2021-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_hub', '0021_auto_20210712_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(),
        ),
    ]
